Source map support (#2691)
* Initial support for source map

* Update source map entries generation

* Inject source content to source map file
Use data-uri for source map (no separate files, map is encoded to base64 and injected to javascript file)

* Generate entry points for statements only

* Exclude declarations and block from entries

* Make method for source map generation public

* Correct merge 45f7d1f3585145e56752bb617805c0d3df542aa9

* Update Client test output (Release mode)

* Remove redundant SourceMap bridge.json config options - just bool SourceMap for now; Use constant for new line "\n"; Formatting

* Exception handling for GenerateSourceMap

* Integration Test: for options "combineScripts": true (02) - Failing, no sourceMap, "outputFormatting": "Minified" (03) - Passing and "outputFormatting": "Formatted" (05) - Failing (removes empty lines)

* Client test Batch1: enable sourceMap - Failing (compile error)
Error: exception level: 0 - An item with the same key has already been added.
  Stack trace:
     at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
     at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
     at Bridge.Translator.Inspector.VisitFieldDeclaration(FieldDeclaration fieldDeclaration) in C:\NET\BridgeNew\Bridge\Compiler\Translator\Inspector\Inspector.Visitor.cs:line 240
     at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor) in C:\NET\BridgeNew\Bridge\Compiler\Contract\Helpers.cs:line 21
     at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration) in C:\NET\BridgeNew\Bridge\Compiler\Translator\Inspector\Inspector.Visitor.cs:line 133
     at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration) in C:\NET\BridgeNew\Bridge\Compiler\Translator\Inspector\Inspector.Visitor.cs:line 149
     at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration) in C:\NET\BridgeNew\Bridge\Compiler\Translator\Inspector\Inspector.Visitor.cs:line 149
     at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor) in C:\NET\BridgeNew\Bridge\Compiler\Contract\Helpers.cs:line 21
     at Bridge.Translator.Inspector.VisitNamespaceDeclaration(NamespaceDeclaration namespaceDeclaration) in C:\NET\BridgeNew\Bridge\Compiler\Translator\Inspector\Inspector.Visitor.cs:line 41
     at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor) in C:\NET\BridgeNew\Bridge\Compiler\Contract\Helpers.cs:line 21
     at Bridge.Translator.Translator.InspectTypes(MemberResolver resolver, IAssemblyInfo config) in C:\NET\BridgeNew\Bridge\Compiler\Translator\Translator\Translator.InspectAssembly.cs:line 257

* Formatting

* Pkg cache reset

* Integration test reference reset: 02 should contain SourceMap; 05 should contain empty lines

* Improve IntegrationTest to cut off diff report if too long

* Update Integration Test 02 (SourceMap added when combineScripts)

* Use new TextSource property of SyntaxTree

* Update functionality

* Update Client test output after fix In Bridge.NRefactory

* Update Integration Test reference 02 and 05 after the fix

* Update to Bridge.NRefactory v.5.5.6 and Mono.Cecil v.0.9.6.4

* Reset AppVeyor cache to get new packages

* Improve diff reporting in Integration Tests

* Tracing SourceMap

* Tracing Test 05 772 output

* Force EOLs

* SourceMap config (bool or {enabled, eol}

* Compiler Tests for SourceMap config (bool or {enabled, eol}

* Update to Newtonsoft.Json v.10.0.2

* Restructure JsonConverter tests